### ISSUE TITLE
Fails to build on Xcode 14.1

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1589]
Build fails with a deprecation warning. It seems deprecation warnings have been set to be reported as build errors in the project file:

```
microsoft-authentication-library-for-objc/MSAL/src/configuration/MSALCacheConfig.m:105:14: error: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.10 - SecKeychain is deprecated [-Werror,-Wdeprecated-declarations]
    status = SecTrustedApplicationCreateFromPath(nil, &myself);
```

**Comment by swasti29** [comment]
@guidedways 
We will be resolving the issue in our next version to support xcode 14 and above.

**Comment by swasti29** [comment]
@guidedways This has been fixed in latest release.
