### ISSUE TITLE
MSAL Build Failed Task failed with exit code 65

### ISSUE THREAD

**Issue by MirceaX2Mobile** [AzureAD/microsoft-authentication-library-for-objc#1039]
Hello! After the last commit (2 days ago) on **master**: Merge pull request #1034 from AzureAD/hotfix/1.1.7 I'm getting:
Building scheme "MSAL (Mac Framework)" in MSAL.xcworkspace
Build Failed
	Task failed with exit code 65:
**This usually indicates that project itself failed to compile**

I tried removing the the Carthage folder and run update again,  but it doesn't work. I tried removing the derived data from Carthage, but still not working.
It works with the "release/1.1.6" branch, but not with master anymore.

**Below is the file that causes MSAL to fail:**

/microsoft-authentication-library-for-objc/MSAL/src/util/mac/MSALRedirectUriVerifier.m

authentication-library-for-objc/MSAL/src/util/mac/MSALRedirectUriVerifier.m:35:57: error: unused parameter 'bypassRedirectValidation' [-Werror,-Wunused-parameter]
                         bypassRedirectValidation:(BOOL)bypassRedirectValidation
                                                        ^
1 error generated.

I hope you can help me, thank you!

**Comment by hieunguyenmsft** [comment]
Hi @MirceaX2Mobile, thanks for reporting the issue. 
I just tried to create a test Mac App with Carthage, MSAL pointing to the 'master' branch and didn't get any issue. Could you share your current build setting and your Carthage file?

**Comment by MirceaX2Mobile** [comment]
I'm having trouble with an iOS app, not with a Mac App. I don't know why the error comes from MSAL/src/util/mac/. What build settings do you need?

Cartfile:
github "AzureAD/microsoft-authentication-library-for-objc" "master"
github "box/box-ios-sdk"
